### ISSUE TITLE
Cannot run the evaluate code

### ISSUE THREAD

**Issue by angelita277** [YouHuang67/focsam#3]
When running the evaluation with
 `export PYTHONPATH=.
python tools/test_no_viz.py configs/_base_/eval_davis.py work_dirs/focsam/focsam_vit_huge_eval/iter_160000.pth`
there is an error:
`KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'test_cfg\': {\'num_clicks\': 20}}\nNone'`
The error is saying that the config in `configs/_base_/eval_davis.py`, that
`test_cfg = dict(_delete_=True, type='ClickTestLoop')
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', scale_factor=1.0, keep_ratio=True),
    dict(type='ObjectSampler',
         max_num_merged_objects=1,
         min_area_ratio=0.0),
    dict(type='PackSegInputs')
]
test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='DAVISDataset',
        data_root='data/davis',
        pipeline=test_pipeline))
test_evaluator = dict()
model = dict(test_cfg=dict(num_clicks=20))

`
the model doesn't have a type. So what is the type?

**Comment by YouHuang67** [comment]
Apologies for the inconvenience. I've updated the `work_dirs` folder and provided two `.py` files which are configuration files for testing the model. When testing, after providing the path to the weights, the script automatically searches for .py files under the weight path. These files are then merged with the provided dataset configuration file to form the complete final configuration file.

**Comment by angelita277** [comment]
Then there's new error...
I ran the test code with
 `export PYTHONPATH=.
python tools/test_no_viz.py configs/_base_/eval_davis.py work_dirs/focsam/focsam_vit_huge_eval/iter_160000.pth`


But received:
`Traceback (most recent call last):
  File "/data2/code/laq/focsam/tools/test_no_viz.py", line 134, in <module>
    main()
  File "/data2/code/laq/focsam/tools/test_no_viz.py", line 130, in main
    runner.test()
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/runner/runner.py", line 1816, in test
    self._test_loop = self.build_test_loop(self._test_loop)  # type: ignore
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/runner/runner.py", line 1604, in build_test_loop
    loop = LOOPS.build(
           ^^^^^^^^^^^^
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
          ^^^^^^^^^^^^^^^
  File "/data2/code/laq/focsam/focsam/runners/click_test_loops.py", line 19, in __init__
    super(ClickTestLoop, self).__init__(runner, dataloader, evaluator)
  File "/data2/code/laq/focsam/engine/runners/base_test_loops.py", line 13, in __init__
    super(BaseTestLoop, self).__init__(runner, dataloader)
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
          ^^^^^^^^^^^^^^^
  File "/data2/code/laq/focsam/engine/datasets/test/davis.py", line 21, in __init__
    super(DAVISDataset, self).__init__(
  File "/data2/code/laq/focsam/engine/datasets/base.py", line 51, in __init__
    self.full_init()
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/dataset/base_dataset.py", line 309, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laq/anaconda3/envs/focsam11/lib/python3.11/site-packages/mmengine/dataset/base_dataset.py", line 771, in _serialize_data
    data_bytes = np.concatenate(data_list)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate`


All of other codes is directly cloned and I didn't change.
Does anyone know the reason?

**Comment by YouHuang67** [comment]
This appears to be an issue with data preparation. Please ensure that your data is set up according to DATASETS.md, and also pay attention to the cached data under data/meta-info. If the data is not loaded correctly, incorrect cache files may be generated here. Additionally, if the cache is incorrect, directly delete the cache files for the corresponding dataset.

**Comment by angelita277** [comment]
Thanks! In the beginning, the data is not set up according to DATASET.md, so I rearranged it, but still not work. Then I found that the file 'davis.json' under 'data/meta-info' is empty because of the wrong arrangement in the beginning. So I delete the 'davis.json', and re-run the code. It works!
